/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ConsoleIndexRouteImport } from "./routes/console/index";
import { Route as PostsIdRouteImport } from "./routes/posts.$id";
import { Route as ConsolePostsRouteImport } from "./routes/console/posts";

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: "/console/",
  path: "/console/",
  getParentRoute: () => rootRouteImport,
} as any);
const PostsIdRoute = PostsIdRouteImport.update({
  id: "/posts/$id",
  path: "/posts/$id",
  getParentRoute: () => rootRouteImport,
} as any);
const ConsolePostsRoute = ConsolePostsRouteImport.update({
  id: "/console/posts",
  path: "/console/posts",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRoute;
  "/login": typeof LoginRoute;
  "/console/posts": typeof ConsolePostsRoute;
  "/posts/$id": typeof PostsIdRoute;
  "/console/": typeof ConsoleIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRoute;
  "/login": typeof LoginRoute;
  "/console/posts": typeof ConsolePostsRoute;
  "/posts/$id": typeof PostsIdRoute;
  "/console": typeof ConsoleIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/dashboard": typeof DashboardRoute;
  "/login": typeof LoginRoute;
  "/console/posts": typeof ConsolePostsRoute;
  "/posts/$id": typeof PostsIdRoute;
  "/console/": typeof ConsoleIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/dashboard" | "/login" | "/console/posts" | "/posts/$id" | "/console/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/dashboard" | "/login" | "/console/posts" | "/posts/$id" | "/console";
  id: "__root__" | "/" | "/dashboard" | "/login" | "/console/posts" | "/posts/$id" | "/console/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DashboardRoute: typeof DashboardRoute;
  LoginRoute: typeof LoginRoute;
  ConsolePostsRoute: typeof ConsolePostsRoute;
  PostsIdRoute: typeof PostsIdRoute;
  ConsoleIndexRoute: typeof ConsoleIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/console/": {
      id: "/console/";
      path: "/console";
      fullPath: "/console/";
      preLoaderRoute: typeof ConsoleIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/posts/$id": {
      id: "/posts/$id";
      path: "/posts/$id";
      fullPath: "/posts/$id";
      preLoaderRoute: typeof PostsIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/console/posts": {
      id: "/console/posts";
      path: "/console/posts";
      fullPath: "/console/posts";
      preLoaderRoute: typeof ConsolePostsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ConsolePostsRoute: ConsolePostsRoute,
  PostsIdRoute: PostsIdRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
